# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 466bb8fdcc669262b018abc0a457bda44499d167e0ce3e5c5d9c1205e2f6ab7f687fcf73a75d792d69e0376ed3c090481634c35169d4d014c572472c134f77f9

test:
  secret_key_base: bdd2a78fcc7e47bdf6814bec0fa428b3e53407705baf303e8b8f3381adfc49533b9e10af6287a68e18ec8c450ceb940319fd1fd8def91f0bdc59266cf9495b31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
